[tool.poetry]
name = "iosducocliwallet"
version = "0.1.0"
description = ""
authors = ["PrianshMittra <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
ducoapi = "^0.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
